name: example
author: Dart Team <misc@dartlang.org>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  channel_annotation: ^0.0.1

dev_dependencies:
  build_runner: ^1.0.0
  channel_serializable: ^0.0.1

  # Used by tests. Not required to use `channel_serializable`.
  build_verify: ^1.0.0
  path: ^1.5.1
  test: ^1.6.0

dependency_overrides:
  channel_annotation:
    path: ../channel_annotation
  channel_serializable:
    path: ../channel_serializable
